# Generated by Django 4.1 on 2023-11-04 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_date', models.DateField(null=True)),
                ('updated_date', models.DateField(null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title_of_video', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('video_image', models.CharField(max_length=20)),
                ('views', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
