# Generated by Django 4.1 on 2023-11-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='type',
            new_name='tag',
        ),
    ]
