# Generated by Django 4.1 on 2023-11-04 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_of_video',
        ),
        migrations.RemoveField(
            model_name='category',
            name='video_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='views',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('created_date', models.DateField(null=True)),
                ('updated_date', models.DateField(null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title_of_video', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('video_image', models.CharField(max_length=20)),
                ('views', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
